name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Packages
        run: apt-get install fontforge
      - name: Run a one-line script
        run: fd . $PWD/proggyfonts -e ttf --exec fontforge --script nerd-fonts/font-patcher -c -l -s -out output/ {} || "Error!" && exit
