name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: snickerbockers/submodules-init@v4
      - name: Prepare Image
        run: |
          sudo apt-get update -y -q
          sudo apt-get install software-properties-common python3-fontforge
      - name: Install Packages
        run: |
          sudo apt-get install -y libjpeg-dev libtiff5-dev \
          libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev \
          libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev \
          python3-dev ninja-build cmake build-essential gettext \
          libuninameslist-dev fontforge -y -q
      - name: Run a one-line script
        run: find . $PWD/proggyfonts/ -name "*.ttf" -exec fontforge FontPatcher/font-patcher -c -l -out output/ {} \;
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: output/
