name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Packages
        run: |
          sudo apt update -y -q
          sudo apt install software-properties-common -y -q
          sudo apt install python3-fontforge -y -q
      - name: Install FontForge
        run: |
          sudo apt install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev python3-dev ninja-build cmake build-essential gettext libuninameslist-dev fontforge fd -y -q
      - name: Run a one-line script
        run: fd . $PWD/proggyfonts -e ttf --exec fontforge --script nerd-fonts/font-patcher -c -l -s -out output/ {} || "Error!" && exit
